# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: system                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'AddOn f端r DB-Plugin mit mysql driver f端r Datenauswertung'
        en: 'AddOn for DB-Plugin using mysql driver for data evaluation'
    maintainer: sisamiwe
#    tester:                         # Who tests this plugin?
    state: develop                  # change to ready when done with development
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.8              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: false           # plugin supports multi instance
    restartable: unknown
    classname: DatabaseAddOn        # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    param1:
        type: str
        description:
            de: 'Demo Parameter'
            en: 'Parameter for demonstration purposes'

item_attributes:
    database_addon_fct:
        type: str
        description:
            de: 'Funktion des AddonPlugins'
            en: ''
        valid_list:
            # Wertehistorie total
            - 'heute'
            - 'woche'
            - 'monat'
            - 'jahr'
            - 'heute_minus1'
            - 'heute_minus2'
            - 'heute_minus3'
            - 'heute_minus4'
            - 'heute_minus5'
            - 'heute_minus6'
            - 'heute_minus7'
            - 'woche_minus1'
            - 'woche_minus2'
            - 'woche_minus3'
            - 'woche_minus4'
            - 'monat_minus1'
            - 'monat_minus2'
            - 'monat_minus3'
            - 'monat_minus4'
            - 'monat_minus12'
            - 'jahr_minus1'
            - 'jahr_minus2'
            - 'rolling_12m_woche_minus1'                       # Verbrauch der letzten 12 Monate ausgehend im Ende der letzten Woche
            - 'rolling_12m_monat_minus1'                       # Verbrauch der letzten 12 Monate ausgehend im Ende des letzten Monats
            - 'rolling_12m_jahr_minus1'                        # Verbrauch der letzten 12 Monate ausgehend im Ende des letzten Jahres
            - 'zaehlerstand_heute'
            - 'zaehlerstand_woche_minus1'
            - 'zaehlerstand_woche_minus2'
            - 'zaehlerstand_woche_minus3'
            - 'zaehlerstand_monat_minus1'
            - 'zaehlerstand_monat_minus2'
            - 'zaehlerstand_monat_minus3'
            - 'zaehlerstand_jahr_minus1'
            - 'zaehlerstand_jahr_minus2'
            - 'zaehlerstand_jahr_minus3'
            # Wertehistorie min/max
            - 'last_24h_min'
            - 'last_24h_max'
            - 'last_24h_avg'
            - 'last_7d_min'
            - 'last_7d_max'
            - 'last_7d_avg'
            - 'heute_min'
            - 'heute_max'
            - 'heute_avg'
            - 'woche_min'
            - 'woche_max'
            - 'woche_avg'
            - 'heute_minus1_min'
            - 'heute_minus1_max'
            - 'heute_minus1_avg'
            - 'heute_minus2_min'
            - 'heute_minus2_max'
            - 'heute_minus2_avg'
            - 'woche_minus1_min'
            - 'woche_minus1_max'
            - 'woche_minus1_avg'
            - 'woche_minus2_min'
            - 'woche_minus2_max'
            - 'woche_minus2_avg'
            - 'monat_min'
            - 'monat_max'
            - 'monat_avg'
            - 'monat_minus1_min'
            - 'monat_minus1_min'
            - 'monat_minus1_min'
            - 'monat_minus2_min'
            - 'monat_minus2_min'
            - 'monat_minus2_min'
            - 'jahr_min'
            - 'jahr_max'
            - 'jahr_avg'
            - 'jahr_minus1_min'
            - 'jahr_minus1_max'
            - 'jahr_minus1_avg'
            # general
            - 'oldest_value'
            - 'oldest_log'
            - 'db_version'
            - 'kaeltesumme'
            - 'waermesumme'
            - 'gruendlandtempsumme'

    database_addon_params:
        type: str
        description:
            de: "Parameter f端r eine Funktion des AddonPlugins im Format **kwargs ('keyword'='argument', 'keyword'='argument', ...)"
            en: ''

    database_addon_startup:
        type: bool
        description:
            de: 'Ausf端hren der Berechung bei PluginStart (delay)'
            en: ''

item_structs: NONE

item_attribute_prefixes: NONE

plugin_functions: NONE

logic_parameters: NONE